package com.kongzhong.gw2.onepercentbg.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ItemsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_yizhestore_item
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_yizhestore_item
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_yizhestore_item
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yizhestore_item
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public ItemsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yizhestore_item
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yizhestore_item
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yizhestore_item
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yizhestore_item
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yizhestore_item
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yizhestore_item
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yizhestore_item
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yizhestore_item
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yizhestore_item
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yizhestore_item
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_yizhestore_item
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProductidIsNull() {
            addCriterion("productid is null");
            return (Criteria) this;
        }

        public Criteria andProductidIsNotNull() {
            addCriterion("productid is not null");
            return (Criteria) this;
        }

        public Criteria andProductidEqualTo(Integer value) {
            addCriterion("productid =", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidNotEqualTo(Integer value) {
            addCriterion("productid <>", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidGreaterThan(Integer value) {
            addCriterion("productid >", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidGreaterThanOrEqualTo(Integer value) {
            addCriterion("productid >=", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidLessThan(Integer value) {
            addCriterion("productid <", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidLessThanOrEqualTo(Integer value) {
            addCriterion("productid <=", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidIn(List<Integer> values) {
            addCriterion("productid in", values, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidNotIn(List<Integer> values) {
            addCriterion("productid not in", values, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidBetween(Integer value1, Integer value2) {
            addCriterion("productid between", value1, value2, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidNotBetween(Integer value1, Integer value2) {
            addCriterion("productid not between", value1, value2, "productid");
            return (Criteria) this;
        }

        public Criteria andGiftnameIsNull() {
            addCriterion("giftname is null");
            return (Criteria) this;
        }

        public Criteria andGiftnameIsNotNull() {
            addCriterion("giftname is not null");
            return (Criteria) this;
        }

        public Criteria andGiftnameEqualTo(String value) {
            addCriterion("giftname =", value, "giftname");
            return (Criteria) this;
        }

        public Criteria andGiftnameNotEqualTo(String value) {
            addCriterion("giftname <>", value, "giftname");
            return (Criteria) this;
        }

        public Criteria andGiftnameGreaterThan(String value) {
            addCriterion("giftname >", value, "giftname");
            return (Criteria) this;
        }

        public Criteria andGiftnameGreaterThanOrEqualTo(String value) {
            addCriterion("giftname >=", value, "giftname");
            return (Criteria) this;
        }

        public Criteria andGiftnameLessThan(String value) {
            addCriterion("giftname <", value, "giftname");
            return (Criteria) this;
        }

        public Criteria andGiftnameLessThanOrEqualTo(String value) {
            addCriterion("giftname <=", value, "giftname");
            return (Criteria) this;
        }

        public Criteria andGiftnameLike(String value) {
            addCriterion("giftname like", value, "giftname");
            return (Criteria) this;
        }

        public Criteria andGiftnameNotLike(String value) {
            addCriterion("giftname not like", value, "giftname");
            return (Criteria) this;
        }

        public Criteria andGiftnameIn(List<String> values) {
            addCriterion("giftname in", values, "giftname");
            return (Criteria) this;
        }

        public Criteria andGiftnameNotIn(List<String> values) {
            addCriterion("giftname not in", values, "giftname");
            return (Criteria) this;
        }

        public Criteria andGiftnameBetween(String value1, String value2) {
            addCriterion("giftname between", value1, value2, "giftname");
            return (Criteria) this;
        }

        public Criteria andGiftnameNotBetween(String value1, String value2) {
            addCriterion("giftname not between", value1, value2, "giftname");
            return (Criteria) this;
        }

        public Criteria andPoint5IsNull() {
            addCriterion("point5 is null");
            return (Criteria) this;
        }

        public Criteria andPoint5IsNotNull() {
            addCriterion("point5 is not null");
            return (Criteria) this;
        }

        public Criteria andPoint5EqualTo(Integer value) {
            addCriterion("point5 =", value, "point5");
            return (Criteria) this;
        }

        public Criteria andPoint5NotEqualTo(Integer value) {
            addCriterion("point5 <>", value, "point5");
            return (Criteria) this;
        }

        public Criteria andPoint5GreaterThan(Integer value) {
            addCriterion("point5 >", value, "point5");
            return (Criteria) this;
        }

        public Criteria andPoint5GreaterThanOrEqualTo(Integer value) {
            addCriterion("point5 >=", value, "point5");
            return (Criteria) this;
        }

        public Criteria andPoint5LessThan(Integer value) {
            addCriterion("point5 <", value, "point5");
            return (Criteria) this;
        }

        public Criteria andPoint5LessThanOrEqualTo(Integer value) {
            addCriterion("point5 <=", value, "point5");
            return (Criteria) this;
        }

        public Criteria andPoint5In(List<Integer> values) {
            addCriterion("point5 in", values, "point5");
            return (Criteria) this;
        }

        public Criteria andPoint5NotIn(List<Integer> values) {
            addCriterion("point5 not in", values, "point5");
            return (Criteria) this;
        }

        public Criteria andPoint5Between(Integer value1, Integer value2) {
            addCriterion("point5 between", value1, value2, "point5");
            return (Criteria) this;
        }

        public Criteria andPoint5NotBetween(Integer value1, Integer value2) {
            addCriterion("point5 not between", value1, value2, "point5");
            return (Criteria) this;
        }

        public Criteria andPoint6IsNull() {
            addCriterion("point6 is null");
            return (Criteria) this;
        }

        public Criteria andPoint6IsNotNull() {
            addCriterion("point6 is not null");
            return (Criteria) this;
        }

        public Criteria andPoint6EqualTo(Integer value) {
            addCriterion("point6 =", value, "point6");
            return (Criteria) this;
        }

        public Criteria andPoint6NotEqualTo(Integer value) {
            addCriterion("point6 <>", value, "point6");
            return (Criteria) this;
        }

        public Criteria andPoint6GreaterThan(Integer value) {
            addCriterion("point6 >", value, "point6");
            return (Criteria) this;
        }

        public Criteria andPoint6GreaterThanOrEqualTo(Integer value) {
            addCriterion("point6 >=", value, "point6");
            return (Criteria) this;
        }

        public Criteria andPoint6LessThan(Integer value) {
            addCriterion("point6 <", value, "point6");
            return (Criteria) this;
        }

        public Criteria andPoint6LessThanOrEqualTo(Integer value) {
            addCriterion("point6 <=", value, "point6");
            return (Criteria) this;
        }

        public Criteria andPoint6In(List<Integer> values) {
            addCriterion("point6 in", values, "point6");
            return (Criteria) this;
        }

        public Criteria andPoint6NotIn(List<Integer> values) {
            addCriterion("point6 not in", values, "point6");
            return (Criteria) this;
        }

        public Criteria andPoint6Between(Integer value1, Integer value2) {
            addCriterion("point6 between", value1, value2, "point6");
            return (Criteria) this;
        }

        public Criteria andPoint6NotBetween(Integer value1, Integer value2) {
            addCriterion("point6 not between", value1, value2, "point6");
            return (Criteria) this;
        }

        public Criteria andPoint7IsNull() {
            addCriterion("point7 is null");
            return (Criteria) this;
        }

        public Criteria andPoint7IsNotNull() {
            addCriterion("point7 is not null");
            return (Criteria) this;
        }

        public Criteria andPoint7EqualTo(Integer value) {
            addCriterion("point7 =", value, "point7");
            return (Criteria) this;
        }

        public Criteria andPoint7NotEqualTo(Integer value) {
            addCriterion("point7 <>", value, "point7");
            return (Criteria) this;
        }

        public Criteria andPoint7GreaterThan(Integer value) {
            addCriterion("point7 >", value, "point7");
            return (Criteria) this;
        }

        public Criteria andPoint7GreaterThanOrEqualTo(Integer value) {
            addCriterion("point7 >=", value, "point7");
            return (Criteria) this;
        }

        public Criteria andPoint7LessThan(Integer value) {
            addCriterion("point7 <", value, "point7");
            return (Criteria) this;
        }

        public Criteria andPoint7LessThanOrEqualTo(Integer value) {
            addCriterion("point7 <=", value, "point7");
            return (Criteria) this;
        }

        public Criteria andPoint7In(List<Integer> values) {
            addCriterion("point7 in", values, "point7");
            return (Criteria) this;
        }

        public Criteria andPoint7NotIn(List<Integer> values) {
            addCriterion("point7 not in", values, "point7");
            return (Criteria) this;
        }

        public Criteria andPoint7Between(Integer value1, Integer value2) {
            addCriterion("point7 between", value1, value2, "point7");
            return (Criteria) this;
        }

        public Criteria andPoint7NotBetween(Integer value1, Integer value2) {
            addCriterion("point7 not between", value1, value2, "point7");
            return (Criteria) this;
        }

        public Criteria andPointIsNull() {
            addCriterion("point is null");
            return (Criteria) this;
        }

        public Criteria andPointIsNotNull() {
            addCriterion("point is not null");
            return (Criteria) this;
        }

        public Criteria andPointEqualTo(Integer value) {
            addCriterion("point =", value, "point");
            return (Criteria) this;
        }

        public Criteria andPointNotEqualTo(Integer value) {
            addCriterion("point <>", value, "point");
            return (Criteria) this;
        }

        public Criteria andPointGreaterThan(Integer value) {
            addCriterion("point >", value, "point");
            return (Criteria) this;
        }

        public Criteria andPointGreaterThanOrEqualTo(Integer value) {
            addCriterion("point >=", value, "point");
            return (Criteria) this;
        }

        public Criteria andPointLessThan(Integer value) {
            addCriterion("point <", value, "point");
            return (Criteria) this;
        }

        public Criteria andPointLessThanOrEqualTo(Integer value) {
            addCriterion("point <=", value, "point");
            return (Criteria) this;
        }

        public Criteria andPointIn(List<Integer> values) {
            addCriterion("point in", values, "point");
            return (Criteria) this;
        }

        public Criteria andPointNotIn(List<Integer> values) {
            addCriterion("point not in", values, "point");
            return (Criteria) this;
        }

        public Criteria andPointBetween(Integer value1, Integer value2) {
            addCriterion("point between", value1, value2, "point");
            return (Criteria) this;
        }

        public Criteria andPointNotBetween(Integer value1, Integer value2) {
            addCriterion("point not between", value1, value2, "point");
            return (Criteria) this;
        }

        public Criteria andItemidsIsNull() {
            addCriterion("itemids is null");
            return (Criteria) this;
        }

        public Criteria andItemidsIsNotNull() {
            addCriterion("itemids is not null");
            return (Criteria) this;
        }

        public Criteria andItemidsEqualTo(String value) {
            addCriterion("itemids =", value, "itemids");
            return (Criteria) this;
        }

        public Criteria andItemidsNotEqualTo(String value) {
            addCriterion("itemids <>", value, "itemids");
            return (Criteria) this;
        }

        public Criteria andItemidsGreaterThan(String value) {
            addCriterion("itemids >", value, "itemids");
            return (Criteria) this;
        }

        public Criteria andItemidsGreaterThanOrEqualTo(String value) {
            addCriterion("itemids >=", value, "itemids");
            return (Criteria) this;
        }

        public Criteria andItemidsLessThan(String value) {
            addCriterion("itemids <", value, "itemids");
            return (Criteria) this;
        }

        public Criteria andItemidsLessThanOrEqualTo(String value) {
            addCriterion("itemids <=", value, "itemids");
            return (Criteria) this;
        }

        public Criteria andItemidsLike(String value) {
            addCriterion("itemids like", value, "itemids");
            return (Criteria) this;
        }

        public Criteria andItemidsNotLike(String value) {
            addCriterion("itemids not like", value, "itemids");
            return (Criteria) this;
        }

        public Criteria andItemidsIn(List<String> values) {
            addCriterion("itemids in", values, "itemids");
            return (Criteria) this;
        }

        public Criteria andItemidsNotIn(List<String> values) {
            addCriterion("itemids not in", values, "itemids");
            return (Criteria) this;
        }

        public Criteria andItemidsBetween(String value1, String value2) {
            addCriterion("itemids between", value1, value2, "itemids");
            return (Criteria) this;
        }

        public Criteria andItemidsNotBetween(String value1, String value2) {
            addCriterion("itemids not between", value1, value2, "itemids");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andGaapidIsNull() {
            addCriterion("gaapid is null");
            return (Criteria) this;
        }

        public Criteria andGaapidIsNotNull() {
            addCriterion("gaapid is not null");
            return (Criteria) this;
        }

        public Criteria andGaapidEqualTo(Integer value) {
            addCriterion("gaapid =", value, "gaapid");
            return (Criteria) this;
        }

        public Criteria andGaapidNotEqualTo(Integer value) {
            addCriterion("gaapid <>", value, "gaapid");
            return (Criteria) this;
        }

        public Criteria andGaapidGreaterThan(Integer value) {
            addCriterion("gaapid >", value, "gaapid");
            return (Criteria) this;
        }

        public Criteria andGaapidGreaterThanOrEqualTo(Integer value) {
            addCriterion("gaapid >=", value, "gaapid");
            return (Criteria) this;
        }

        public Criteria andGaapidLessThan(Integer value) {
            addCriterion("gaapid <", value, "gaapid");
            return (Criteria) this;
        }

        public Criteria andGaapidLessThanOrEqualTo(Integer value) {
            addCriterion("gaapid <=", value, "gaapid");
            return (Criteria) this;
        }

        public Criteria andGaapidIn(List<Integer> values) {
            addCriterion("gaapid in", values, "gaapid");
            return (Criteria) this;
        }

        public Criteria andGaapidNotIn(List<Integer> values) {
            addCriterion("gaapid not in", values, "gaapid");
            return (Criteria) this;
        }

        public Criteria andGaapidBetween(Integer value1, Integer value2) {
            addCriterion("gaapid between", value1, value2, "gaapid");
            return (Criteria) this;
        }

        public Criteria andGaapidNotBetween(Integer value1, Integer value2) {
            addCriterion("gaapid not between", value1, value2, "gaapid");
            return (Criteria) this;
        }

        public Criteria andImgurlIsNull() {
            addCriterion("imgurl is null");
            return (Criteria) this;
        }

        public Criteria andImgurlIsNotNull() {
            addCriterion("imgurl is not null");
            return (Criteria) this;
        }

        public Criteria andImgurlEqualTo(String value) {
            addCriterion("imgurl =", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlNotEqualTo(String value) {
            addCriterion("imgurl <>", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlGreaterThan(String value) {
            addCriterion("imgurl >", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlGreaterThanOrEqualTo(String value) {
            addCriterion("imgurl >=", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlLessThan(String value) {
            addCriterion("imgurl <", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlLessThanOrEqualTo(String value) {
            addCriterion("imgurl <=", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlLike(String value) {
            addCriterion("imgurl like", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlNotLike(String value) {
            addCriterion("imgurl not like", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlIn(List<String> values) {
            addCriterion("imgurl in", values, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlNotIn(List<String> values) {
            addCriterion("imgurl not in", values, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlBetween(String value1, String value2) {
            addCriterion("imgurl between", value1, value2, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlNotBetween(String value1, String value2) {
            addCriterion("imgurl not between", value1, value2, "imgurl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_yizhestore_item
     *
     * @mbggenerated do_not_delete_during_merge Wed Dec 16 14:38:10 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_yizhestore_item
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}