package com.kongzhong.gw2.onepercentbg.domain;

import java.util.Date;

public class Items {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yizhestore_item.id
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yizhestore_item.productid
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    private Integer productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yizhestore_item.giftname
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    private String giftname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yizhestore_item.point5
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    private Integer point5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yizhestore_item.point6
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    private Integer point6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yizhestore_item.point7
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    private Integer point7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yizhestore_item.point
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    private Integer point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yizhestore_item.itemids
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    private String itemids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yizhestore_item.createtime
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yizhestore_item.status
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yizhestore_item.gaapid
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    private Integer gaapid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yizhestore_item.imgurl
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    private String imgurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yizhestore_item.id
     *
     * @return the value of t_yizhestore_item.id
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yizhestore_item.id
     *
     * @param id the value for t_yizhestore_item.id
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yizhestore_item.productid
     *
     * @return the value of t_yizhestore_item.productid
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yizhestore_item.productid
     *
     * @param productid the value for t_yizhestore_item.productid
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yizhestore_item.giftname
     *
     * @return the value of t_yizhestore_item.giftname
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public String getGiftname() {
        return giftname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yizhestore_item.giftname
     *
     * @param giftname the value for t_yizhestore_item.giftname
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public void setGiftname(String giftname) {
        this.giftname = giftname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yizhestore_item.point5
     *
     * @return the value of t_yizhestore_item.point5
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public Integer getPoint5() {
        return point5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yizhestore_item.point5
     *
     * @param point5 the value for t_yizhestore_item.point5
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public void setPoint5(Integer point5) {
        this.point5 = point5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yizhestore_item.point6
     *
     * @return the value of t_yizhestore_item.point6
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public Integer getPoint6() {
        return point6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yizhestore_item.point6
     *
     * @param point6 the value for t_yizhestore_item.point6
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public void setPoint6(Integer point6) {
        this.point6 = point6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yizhestore_item.point7
     *
     * @return the value of t_yizhestore_item.point7
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public Integer getPoint7() {
        return point7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yizhestore_item.point7
     *
     * @param point7 the value for t_yizhestore_item.point7
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public void setPoint7(Integer point7) {
        this.point7 = point7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yizhestore_item.point
     *
     * @return the value of t_yizhestore_item.point
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yizhestore_item.point
     *
     * @param point the value for t_yizhestore_item.point
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yizhestore_item.itemids
     *
     * @return the value of t_yizhestore_item.itemids
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public String getItemids() {
        return itemids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yizhestore_item.itemids
     *
     * @param itemids the value for t_yizhestore_item.itemids
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public void setItemids(String itemids) {
        this.itemids = itemids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yizhestore_item.createtime
     *
     * @return the value of t_yizhestore_item.createtime
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yizhestore_item.createtime
     *
     * @param createtime the value for t_yizhestore_item.createtime
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yizhestore_item.status
     *
     * @return the value of t_yizhestore_item.status
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yizhestore_item.status
     *
     * @param status the value for t_yizhestore_item.status
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yizhestore_item.gaapid
     *
     * @return the value of t_yizhestore_item.gaapid
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public Integer getGaapid() {
        return gaapid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yizhestore_item.gaapid
     *
     * @param gaapid the value for t_yizhestore_item.gaapid
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public void setGaapid(Integer gaapid) {
        this.gaapid = gaapid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yizhestore_item.imgurl
     *
     * @return the value of t_yizhestore_item.imgurl
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yizhestore_item.imgurl
     *
     * @param imgurl the value for t_yizhestore_item.imgurl
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }
}