package com.kongzhong.gw2.onepercentbg.mapper;

import com.kongzhong.gw2.onepercentbg.domain.Items;
import com.kongzhong.gw2.onepercentbg.domain.ItemsExample;
import com.kongzhong.gw2.onepercentbg.domain.Page;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yizhestore_item
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    int countByExample(ItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yizhestore_item
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    int deleteByExample(ItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yizhestore_item
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yizhestore_item
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    int insert(Items record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yizhestore_item
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    int insertSelective(Items record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yizhestore_item
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    List<Items> selectByExample(ItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yizhestore_item
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    Items selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yizhestore_item
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    int updateByExampleSelective(@Param("record") Items record, @Param("example") ItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yizhestore_item
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    int updateByExample(@Param("record") Items record, @Param("example") ItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yizhestore_item
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    int updateByPrimaryKeySelective(Items record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yizhestore_item
     *
     * @mbggenerated Wed Dec 16 14:38:10 CST 2015
     */
    int updateByPrimaryKey(Items record);
    
    List<Items> findAll(Page page);
}